language: c
sudo: required
dist: trusty

compiler:
  - clang

os:
  - linux
  - osx

env:
  #  matrix:
  global:
    - LUA_VERSION=LUA53 LLVM_VERSION="4.0"
    - LUA_VERSION=LUA52 LLVM_VERSION="4.0"
    - LUA_VERSION=LUA51 LLVM_VERSION="4.0"

before_install:
  - export PATH="$TRAVIS_BUILD_DIR/install/bin:$TRAVIS_BUILD_DIR/install/latest-llvm-symlinks:$PATH"
  - PREFIX="$TRAVIS_BUILD_DIR/install" PLAT="${TRAVIS_OS_NAME/osx/macosx}" TMPSRC="$TRAVIS_BUILD_DIR/.src" .travis/install_lua.sh
  - PREFIX="$TRAVIS_BUILD_DIR/install" .travis/install_llvm.sh
  - ls -lah $TRAVIS_BUILD_DIR/install
  - ls -lah $TRAVIS_BUILD_DIR/install/latest-llvm-symlinks


install:
  - luarocks install --local busted
  - luarocks install --local luacov
  - luarocks install --local luacov-coveralls

script:
  - mkdir build && pushd build
  - cmake -D USE_PRE_GENERATED_BINDINGS=FALSE \
          -D LUA_INCLUDE_DIR=$TRAVIS_BUILD_DIR/install/include ..
  - make
  - popd
  - luarocks make

test:
  - busted -c -Xhelper travis,env=full --verbose

after_success:
  - bash <(curl -s https://codecov.io/bash)
