language: c
sudo: required
dist: trusty

compiler:
  - clang

env:
  matrix:
    - LUA_VERSION=LUA53
    - LUA_VERSION=LUA52
    - LUA_VERSION=LUA51

before_install:
  - export LLVM_VERSION="4.0"
  - export PREFIX="$TRAVIS_BUILD_DIR/install"
  - export PLAT="${TRAVIS_OS_NAME/osx/macosx}"
  - export PATH="$TRAVIS_BUILD_DIR/install/bin:$PATH"
  - export PATH="$TRAVIS_BUILD_DIR/install/latest-llvm-symlinks:$PATH"
  - export PATH="$HOME/.luarocks/bin:$PATH"

  - TMPSRC="$TRAVIS_BUILD_DIR/.src" .travis/install_lua.sh
  - .travis/install_llvm.sh
  - .travis/install_luanativeobjects.sh

  - eval $(luarocks path --bin)

install:
  - luarocks install --local busted
  - luarocks install --local ldoc
  - luarocks install --local luacov
  - luarocks install --local luacov-coveralls
  - export CC=`which clang-4.0`
  - export CXX=`which clang++-4.0`

script:
  - mkdir build && pushd build
  - cmake -D USE_PRE_GENERATED_BINDINGS=FALSE
          -D GENERATE_LUADOCS=TRUE
          -D LUA_INCLUDE_DIR=$TRAVIS_BUILD_DIR/install/include
          -D LUA_LIBRARIES=$TRAVIS_BUILD_DIR/install/lib ..
  - make
  - popd

  - make ci-test
  - make doc

after_success:
  - bash <(curl -s https://codecov.io/bash)
